--- 
abstract: AnyEvent based semaphores
author: 
  - Anders Nor Berle <berle@cpan.org>
build_requires: 
  Coro: 4.45
  Test::More: 0.72
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: AnyEvent-Semaphore
no_index: 
  directory: 
    - inc
    - t
requires: 
  AnyEvent: 2.9
  Scope::Guard: 0.03
version: 0.00_01
